### ISSUE TITLE
[bug] error handle `nvim_set_text`

### ISSUE THREAD

**Issue by akinsho** [aarondiel/spread.nvim#1]
Hi 👋🏿, recently just discovered this plugin, and it seems really cool.

When running the combine or spread functions, I occasionally encounter the following error
```
E5108: Error executing lua: ...are/nvim/site/pack/packer/opt/spread.nvim/lua/spread.lua:145: String cannot contain newlines                                                                     
stack traceback:                                                                                                                                                                                
        [C]: in function 'nvim_buf_set_text'                                                                                                                                                    
        ...are/nvim/site/pack/packer/opt/spread.nvim/lua/spread.lua:145: in function <...are/nvim/site/pack/packer/opt/spread.nvim
```
It seems to happen when I try and combine something that has expanded (with newlines) child nodes e.g.
```dart
Container(
  child: Text(
   "test"
   style: TextStyle()
 )
)
```
Trying to collapse a single item works fine but if there are other items within it that seems to trigger this error.

I think probably the solution would be to recursively collapse everything including children, or swallow the error and notify or not that it won't work 🤷🏿‍♂️

**Comment by aarondiel** [comment]
the plugin uses treesitter and i have not tested it on all to many languages yet, with what languages are you encountering this problem?

**Comment by akinsho** [comment]
@aarondiel so far I've seen it in dart and lua
