### ISSUE TITLE
Just a hint

### ISSUE THREAD

**Issue by leiserfg** [aarondiel/spread.nvim#3]
I use a plugin with a similar objective, https://github.com/AndrewRadev/splitjoin.vim  maybe you can get some ides from it.

**Comment by aarondiel** [comment]
i have seen this plugin prior to starting this project, but have totally forgotten about it, thank you.

there are some things from *splitjoin* that i also want to incorperate into *spread*, for instance automatic testing on multiple languages.

this project could be seen as a lua / treesitter based version of that plugin, becuase i ultimately think it provides a more robust framework for writing these kinds of formatters.
