### ISSUE TITLE
Comparation with other plugins

### ISSUE THREAD

**Issue by pedro757** [aarondiel/spread.nvim#4]
How does this compare to [AndrewRadev/splitjoin.vim](https://github.com/AndrewRadev/splitjoin.vim)?

**Comment by aarondiel** [comment]
this question is similar to #3:

roughly speaking, `spread.nvim` uses lua and treesitter while `splitjoin.vim` uses vimscript and regex.

both plugins try to solve the same issue, the tooling behind it is just different.

i hope that treesitter will provide a more robust tool for formatting, but this plugin is still in development so i have yet to implement a lot of these features.

if you are missing any particular feature found in `splitjoin.vim`, you can open an issue for me to prioritize シ
