### ISSUE TITLE
Trying to add this to which key fails

### ISSUE THREAD

**Issue by thepenguinthatwants** [aarondiel/spread.nvim#5]
Hi,
I am trying to add this function to using lua to which.

`        s = { "<leader>Ss", "<cmd>lua require('spread').out()<cr>", desc = "Spread out" },`

It should work I guess, but for som reasons it still fails. Any clue?

**Comment by aarondiel** [comment]
hi,
i'm currently in the process of restucturing the codebase for spread.nvim.
it could be that i have not implemented any spreading logic for the language you are using (typescript, lua, c definetly work).
but it could also be a problem with you specific nvim config, which i can't tell without further details.
